# Generated by Django 2.2.16 on 2021-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можете добавить картинку', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
